[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "meltanolabs-tap-snowflake"
dynamic = [ "version" ]
description = "Singer tap for Snowflake, built with the Meltano SDK for Singer Taps."
authors = [{ name = "Meltano Team", email = "hello@meltano.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "ELT",
    "Meltano",
    "Snowflake",
]
dependencies = [
    "cryptography>=50",
    "singer-sdk~=0.54.5",
    "snowflake-sqlalchemy==1.11.0",
    "snowflake-connector-python[secure-local-storage]~=4.7.3",
    "sqlalchemy~=2.0.52",
]

[project.scripts]
tap-snowflake = "tap_snowflake.tap:TapSnowflake.cli"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "testing" },
]
lint = [
    "mypy~=2.3",
    "ruff~=0.16.0",
    "ty>=0.0.78",
]
testing = [
    "singer-sdk[testing]",
]

[tool.hatch.version]
fallback-version = "0.0.0.dev0"
source = "vcs"

[tool.uv]
default-groups = "all"
required-version = ">=0.12"

[tool.hatch.build.targets.sdist]
include = ["tap_snowflake"]

[tool.hatch.build.targets.wheel]
include = ["tap_snowflake"]

[tool.ruff]
line-length = 88
required-version = ">=0.16"

[tool.ruff.lint]
ignore = [
    "ANN001",
    "ANN401",
    "COM812",
    "S608",
    "SLF001",
    "EM101",
    "CPY",
]
select = ["ALL"]

[tool.ruff.format]
quote-style = "double"
exclude = ["*.pyi"]

[tool.ruff.lint.isort]
known-first-party = ["target_snowflake"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
follow_untyped_imports = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
