# This file can be used to customize tox tests as well as other test frameworks like flake8 and mypy

[tox]
requires =
    tox>=4.51
    tox-uv
envlist =
    format
    lint
    3.14
isolated_build = true

[testenv]
description = run all tests, linters and type checkers
runner = uv-venv-lock-runner

[testenv:pytest]
description = run pytest to execute the test suite
dependency_groups = testing
envlist = 3.{10-14}
commands =
    pytest

[testenv:format]
description = auto-resolve lint and format errors
dependency_groups = lint
commands =
    ruff check --fix
    ruff format

[testenv:lint]
description = run ruff and mypy to check for lint, format and type errors
dependency_groups = lint
commands =
    ruff check
    ruff format --check
    # refer to [tool.mypy] in pyproject.toml for specific settings
    mypy tap_snowflake
