### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-snowflake

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
    - name: Run lint command from tox.ini
      run: |
        uvx --managed-python --with tox-uv tox -e lint

  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SF_USER: ${{secrets.SF_USER}}
      SF_PASSWORD: ${{secrets.SF_PASSWORD}}
      SF_ACCOUNT: ${{secrets.SF_ACCOUNT}}
      SF_DATABASE: ${{secrets.SF_DATABASE}}
      SF_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
      SF_ROLE: ${{secrets.SF_ROLE}}
    strategy:
      max-parallel: 1
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv sync
    - name: Test with pytest
      run: |
        uv run pytest --capture=no
